### PR TITLE
image pick bug fixed in desktop, android and web

### PR DESCRIPTION
**Pull request by Coding-Meet**
first issues solved it 

[Crash] [Desktop] Selecting non-image file on desktop crashes the app #1

### CODE REVIEW

**Comment by PatilShreyas** [comment]
@Coding-Meet I don't want to change the library for image picking. Because I already tried MPFile Picker but it has issued in iOS and Android that it needs to be parsed manually. Can you fix the issue with same library?

**Comment by Coding-Meet** [comment]
> @Coding-Meet I don't want to change the library for image picking. Because I already tried MPFile Picker but it has issued in iOS and Android that it needs to be parsed manually. Can you fix the issue with same library?

i have no ios device so not check, but i use two library MPFile for desktop, calf file picker for ios and android rememberLauncherForActivityResult use and web side already code perfect works

**Comment by Coding-Meet** [comment]
i also check calf file picker library not work in android and desktop

**Comment by PatilShreyas** [comment]
Please revert the changes of addition of new library as discussed already @Coding-Meet

**Comment by Coding-Meet** [comment]
i build this https://github.com/Coding-Meet/Gemini-AI-KMP-App

**Comment by PatilShreyas** [comment]
Nice @Coding-Meet 👍🏻

**Comment by Coding-Meet** [comment]
i not use your library because i already api code written

**Comment by Coding-Meet** [comment]
remove mdfile picker library and no library use in android, desktop, web. i check prefect works android, desktop, web

**Comment by PatilShreyas** [comment]
@Coding-Meet you're not getting my point. There's no need to make many changes for just a small thing. We could handle an exception on desktop-level platform implementation only. Why change things for other platforms if everything is working fine?

**Comment by Coding-Meet** [comment]
> @Coding-Meet you're not getting my point. There's no need to make many changes for just a small thing. We could handle an exception on desktop-level platform implementation only. Why change things for other platforms if everything is working fine?

your code one problem that solved this. problem was file picker dialog open after that user cancel button click after click dialog show button click but file pick dialog not show. so, i all platform change it i check all platform it work perfect remining ios platform not check

**Comment by PatilShreyas** [comment]
Keep the changes as is (as in base branch). Just handle exceptions in desktop variant. We'll solve for android and other platform issue with different solution.

**Pull request closed without merging**
